name: CI
on:
  pull_request:
    branches: main
jobs:
  CI:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & echo "Started xvfb"
        shell: bash
        if: ${{ success() && matrix.os == 'ubuntu-latest' }}
      - name: Installing
        run: yarn install --frozen-lockfile
      - name: Lerna Bootstrap
        run: npx lerna bootstrap
      - name: Running Lint
        run: yarn lint
      - name: Running Test
        env:
          WAIT_TIME: 2000
          DISPLAY: ':99.0'
        run: |
          npx lerna run build --scope=@sagaroute/react --scope=@sagaroute/cmd
          npx lerna run test
